
services: 
    postgres:
        image: pgvector/pgvector:pg17
        ports:
            - 127.0.0.1:5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgvector_data:/var/lib/postgresql/data

    valkey:
        image: valkey/valkey:latest
        ports:
            - 127.0.0.1:6379:6379
        volumes:
            - valkey_data:/data

    inngest: 
        image: inngest/inngest:latest
        command: inngest dev -u http://host.docker.internal:3000/api/inngest
        ports: 
            - 127.0.0.1:8288:8288
        

volumes:    
  pgvector_data:
  valkey_data: