
services: 
    postgres:
        image: pgvector/pgvector:pg17
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgvector_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d inngest && pg_isready -U postgres -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    valkey:
        image: valkey/valkey:latest
        ports:
            - 6379:6379
        volumes:
            - valkey_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5
           
    inngest: 
        image: inngest/inngest:latest
        command: "inngest start --no-ui"
        ports: 
            - 8288:8288
            - 8289:8289
        environment:
            INNGEST_EVENT_KEY: ${INNGEST_EVENT_KEY}
            INNGEST_SIGNING_KEY: ${INNGEST_SIGNING_KEY}
            INNGEST_POSTGRES_URI: postgres://postgres:postgres@postgres:5432/inngest
            INNGEST_REDIS_URI: redis://valkey:6379
            INNGEST_DEV: 0
        depends_on:
            postgres:
                condition: service_healthy
            valkey:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8288/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
 
    vectorchord: 
        image: ghcr.io/tensorchord/vchord-postgres:pg17-v0.4.3
        ports: 
            - 5433:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - vectorchord_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:    
  pgvector_data:
  valkey_data:  
  vectorchord_data: