
services: 
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data: