/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "McpPlatformBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "McpPlatformBucket-kyle": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "McpPlatformInngestService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "McpPlatformInngestService-kyle": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "McpPlatformNextjs-kyle": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "McpPlatformNextjsApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "McpPlatformPostgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "McpPlatformRedis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "McpPlatformVpc": {
      "type": "sst.aws.Vpc"
    }
    "McpPlatformVpc-kyle": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}